name: "1BitUral майнинг отель"
description: "Дополнение Home Assistant для майнинг отелей"
version: "0.0.4"
slug: "bitural"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
options:
  beer: true
  wine: true
  liquor: false
  name: "world"
  year: 2017
schema:
  beer: bool
  wine: bool
  liquor: bool
  name: str
  year: int
ports:
  8000/tcp: 8000
